name = "frostfire-forge-frontend"
main = "src/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./public"
entry-point = "workers-site"

[env.production]
name = "frostfire-forge-frontend"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "frostfire-forge-frontend-staging"
vars = { ENVIRONMENT = "staging" } 